my_project/blog/urls.py
from django.urls import path

from .views import PostAPIDetail, PostAPIList

urlpatterns = [ 
    path(
        "blog/", PostAPIList.as_view(), name='api-post-list'
    ),

    path(
        'blog/<int:year>/<int:month>/<str:slug>/',
        PostAPIDetail.as_view(),
        name='api-post-detail',
    ),
]

my_project/my_project/urls.py
from django.contrib import admin
from django.urls import path, include

from organizer import urls as organizer_urls
from blog import urls as blog_urls 
from salvador import urls as salvador_urls



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(organizer_urls)),
    path('',include(blog_urls)),
    path('', include(salvador_urls)),
]

my_project/organizer/urls.py
from django.urls import path

from .views import (
    TagApiDetail,
    TagApiList,
    StartupAPIDetail,
    StartupAPIList,
    NewsLinkAPIList,
    NewsLinkAPIDetail,
    )


from .views import TagDetail, TagList

urlpatterns = [
    path('tag/', TagApiList.as_view(), name='api-tag-list' ),

    path('tag/<str:slug>/',
    TagApiDetail.as_view(),
    name='api-tag-detail'
    ),

    path("tag/", TagList.as_view(), name="tag_list"),
    path("tag/<str:slug>/", TagDetail.as_view(), name="tag_detail"),

    path('startup/', StartupAPIList.as_view(), name='api-startup-list'),

    path('startup/<str:slug>/',
    StartupAPIDetail.as_view(),
    name='api-startup-detail'),

    path('newslink/', NewsLinkAPIList.as_view(), name='api-newslink-list'),

    path('newslink/<str:startup_slug>/<str:newslink_slug>/',
    NewsLinkAPIDetail.as_view(),
    name='api-newslink-detail'
    )

]

my_project/salvador/urls.py
from django.urls import path

from .views import (
    TrackApiList,
    AlbumApiList,
)

urlpatterns = [
    path('album/', AlbumApiList.as_view(), name='api-album-list'),

    path('track/',TrackApiList.as_view(), name='api-track-list'),
]

my_project/blog/models.py
from django.db import models

from organizer.models import Startup, Tag

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=63)
    slug = models.SlugField(max_length=63)
    text = models.TextField()
    pub_date = models.DateField()
    tags = models.ManyToManyField(Tag)
    startups = models.ManyToManyField(Startup)

    class Meta:
        get_latest_by = "pub_date"
        ordering = ["-pub_date", "title"]
        verbose_name = "blog post"
    def __str__(self):
        date_string = self.pub_date.strftime("%Y-%m-%d")
        return f"{self.title} on {date_string}" 

my_project/organizer/models.py
from django.db import models

# Create your models here.

class Tag(models.Model):
    name = models.CharField(
        max_length=31,
        unique=True,
    )
    slug = models.SlugField(
        max_length=31,
        unique=True,
        help_text='A label for URL config',
    )

    class Meta:
        ordering = ["name"]

    def __str__(self) -> str:
        return self.name


class Startup(models.Model):
    name = models.CharField(
        max_length=31,
        db_index=True, 
    )
    slug = models.SlugField(
        max_length=31,
        unique=True,
        help_text='A label for URL config',
    )
    description = models.TextField()
    founded_date = models.DateField('date founded')
    contact = models.EmailField()
    website = models.URLField(max_length=255)
    tags = models.ManyToManyField(Tag)

    class Meta:
        get_latest_by = "founded_date"
        ordering = ["name"]

    def __str__(self) -> str:
        return self.name

class NewsLink(models.Model):
    title = models.CharField(max_length=31)
    slug = models.SlugField(max_length=31)
    pub_date = models.DateField('date published')
    link = models.URLField(max_length=255)
    startup = models.ForeignKey(Startup, on_delete=models.CASCADE)

    class Meta:
        get_latest_by = "pub_date"
        ordering = ["-pub_date"]
        unique_together = ("slug","startup")
        verbose_name = "news article"

    def __str__(self) -> str:
        return f"{self.startup}: {self.title}"

my_project/salvador/models.py
from django.db import models

# Create your models here.

class Album(models.Model):
    album_name = models.CharField(max_length=100)
    artist = models.CharField(max_length=100)

class Track(models.Model):
    album = models.ForeignKey(Album, related_name='tracks', on_delete=models.CASCADE)
    order = models.IntegerField()
    title = models.CharField(max_length=100)
    duration = models.IntegerField()

    class Meta:
        unique_together = ('album', 'order')
        ordering = ['order']

    def __unicode__(self):
        return '%d: %s' % (self.order, self.title)

my_project/blog/views.py
from django.shortcuts import render

# Create your views here.

from django.shortcuts import get_object_or_404
from rest_framework.generics import (
    ListAPIView,
    RetrieveAPIView,
)

from .models import Post
from .serializers import PostSerializer


class PostAPIList(ListAPIView):

    queryset = Post.objects.all()
    serializer_class = PostSerializer

class PostAPIDetail(RetrieveAPIView):

    queryset = Post.objects.all()
    serializer_class = PostSerializer

    def get_object(self):
        
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        slug = self.kwargs.get('slug')

        queryset = self.filter_queryset(self.get_queryset())

        post = get_object_or_404(
            queryset,
            pub_date__year=year,
            pub_date__month=month,
            slug=slug,
        )

        self.check_object_permissions(self.request, post)
        return post

my_project/organizer/views.py
import json

import pprint

from django.shortcuts import get_object_or_404
from django.views.generic import DetailView, ListView

from rest_framework.generics import (
    ListAPIView,
    ListCreateAPIView,
    RetrieveAPIView,
)

from rest_framework.response import Response
from rest_framework.status import (
    HTTP_200_OK,
    HTTP_400_BAD_REQUEST,
)




from .serializers import TagSerializer, StartupSerializer, NewsLinkSerializer

from .models import Tag, Startup , NewsLink

# Create your views here.

class TagList(ListView):

    queryset = Tag.objects.all()
    template_name = "tag/list.html"

class TagDetail(DetailView):

    queryset = Tag.objects.all()
    template_name = "tag/detail.html"


class TagApiDetail(RetrieveAPIView):

    queryset = Tag.objects.all()
    serializer_class = TagSerializer
    # detail need a /slug
    lookup_field = 'slug'

    def patch(self, request, slug):
        """ update existing Tag with patch """
        """ using patch method instead of put method """
        tag = self.get_object()
        s_tag = self.serializer_class(
            tag, 
            data=request.data,
            context = {'request': request},
        )
        if s_tag.is_valid():
            s_tag.save()
            return Response(s_tag.data, status=HTTP_200_OK)
        return Response(
            s_tag.errors, status=HTTP_400_BAD_REQUEST
        )



class TagApiList(ListCreateAPIView):

    queryset = Tag.objects.all()
    serializer_class = TagSerializer


# --- Startup ---
class StartupAPIDetail(RetrieveAPIView):

    queryset = Startup.objects.all()
    serializer_class = StartupSerializer
    # detail need a /slug
    lookup_field = 'slug'


class StartupAPIList(ListAPIView):
    
    queryset = Startup.objects.all()
    serializer_class = StartupSerializer
            

# --- it is important & usefull website for Serializer ---
# https://www.cdrf.co/
# --- 

class NewsLinkAPIDetail(RetrieveAPIView):
    queryset = NewsLink.objects.all()
    serializer_class = NewsLinkSerializer 

    # we don't use this form
    # lookup_field = 'slug'

    # instead we use this form 
    # ---> 
    def get_object(self):

        startup_slug = self.kwargs.get('startup_slug')
        newslink_slug = self.kwargs.get('newslink_slug')

        queryset = self.filter_queryset(self.get_queryset())

        newslink = get_object_or_404(
            queryset,
            slug=newslink_slug,
            startup__slug=startup_slug,
        )

        self.check_object_permissions(
            self.request, newslink
        )

        return newslink




class NewsLinkAPIList(ListAPIView):
    queryset = NewsLink.objects.all()
    serializer_class = NewsLinkSerializer

my_project/salvador/views.py
from django.shortcuts import render

from django.shortcuts import get_object_or_404

from rest_framework.generics import (
    ListAPIView,
    RetrieveAPIView
)

from .serializers import TrackSerializer, AlbumSerializer

from .models import Track, Album

# Create your views here.

class TrackApiList(ListAPIView):
    queryset = Track.objects.all()
    serializer_class = TrackSerializer

class AlbumApiList(ListAPIView):
    queryset = Album.objects.all()
    serializer_class = AlbumSerializer

my_project/templates/base.html
<!doctype html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Startup Organizer{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>
  <body>
    <!--[if lte IE 9]>
      <p class="browserupgrade">
        You are using an <strong>outdated</strong> browser. Please
        <a href="https://browsehappy.com/">upgrade your browser</a>
        to improve your experience and security.
      </p>
    <![endif]-->
    <nav>
      <ul>
        <li><a href="{% url 'post_list' %}">Blog</a></li>
        <li><a href="{% url 'startup_list' %}">Startups</a></li>
        <li><a href="{% url 'tag_list' %}">Tags</a></li>
        <li><a href="{% url 'api-root' %}">Browse API</a></li>
      </ul>
    </nav>
    {% block content %}{% endblock %}
    <footer>
      <p>
        Built by
        <a href="https://andrewsforge.com">Andrew Pinkham</a>
        under the
        <a href="https://opensource.org/licenses/BSD-2-Clause">
          Simplified BSD License</a>.
      </p>
    <footer>
  </body>
</html>

my_project/templates/newslink/base.html
{% extends parent_template|default:"base.html" %}

my_project/templates/newslink/confirm_delete.html
{% extends parent_template|default:"newslink/base.html" %}

{% block title %}
  Article for {{ startup.name }}: delete?
{% endblock %}

{% block content %}
  <form
      action="."
      method="post"
  >
    {% csrf_token %}
    <p>
      Are you sure you want to delete the article
      <a href="{{ newslink.link }}">{{ newlink.title }}</a>
      associated with {{ startup.name }}?
    </p>
    <a href="{{ newslink.get_absolute_url }}">
      Cancel
    </a>
    <button type="submit">Delete link to article</button>
  </form>
{% endblock %}

my_project/templates/newslink/form.html
{% extends parent_template|default:"newslink/base.html" %}

{% block title %}
  {{ block.super }} - {% if update %}Update{% else %}Create{% endif %} Article Link
{% endblock %}

{% block content %}
  Link to new article for startup {{ startup.name }}?
  <form
      action="."
      method="post"
  >
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">
      {% if update %}Update{% else %}Create{% endif %} link to article
    </button>
  </form>
{% endblock %}

my_project/templates/post/base.html
{% extends parent_template|default:"base.html" %}

my_project/templates/post/confirm_delete.html
{% extends parent_template|default:"post/base.html" %}

{% block title %}
  {{ post.name }}: delete?
{% endblock %}

{% block content %}
  <form
      action="."
      method="post"
  >
    {% csrf_token %}
    <p>
      Are you sure you want to delete blog post {{ post.name }}?
    </p>
    <a href="{{ post.get_absolute_url }}">
      Cancel
    </a>
    <button type="submit">Delete Blog Post</button>
  </form>
{% endblock %}

my_project/templates/post/detail.html
{% extends parent_template|default:"post/base.html" %}

{% block title %}
  {{ block.super }} - {{ post.title|title }}
{% endblock %}

{% block content %}
  <article>
    <header>
      <h2>{{ post.title|title }}</h2>
      <p>
        Written on
        <time datetime="{{ post.pub_date|date:"Y-m-d" }}">
          {{ post.pub_date|date:"l, F j, Y" }}
        </time>
      </p>
    </header>
    {{ post.text|linebreaks }}
    <ul>
      <li>
        <a href="{{ post.get_update_url }}">
          Update
        </a>
      </li>
      <li>
        <a href="{{ post.get_delete_url }}">
          Delete
        </a>
      </li>
    </ul>
    {% if post.startups.all or post.tags.all %}
      <footer>
        {% with startup_list=post.startups.all %}
          {% if startup_list %}
            <section>
              <h3>Startup{{ startup_list|pluralize }}</h3>
              <ul>
                {% for startup in startup_list %}
                  <li><a href="{{ startup.get_absolute_url }}">
                    {{ startup.name }}
                  </a></li>
                {% endfor %}
              </ul>
            </section>
          {% endif %}
        {% endwith %}
        {% with tag_list=post.tags.all %}
          {% if tag_list %}
            <section>
              <h3>Tag{{ tag_list|pluralize }}</h3>
              <ul>
                {% for tag in tag_list %}
                  <li><a href="{{ tag.get_absolute_url }}">
                    {{ tag.name|title }}
                  </a></li>
                {% endfor %}
              </ul>
            </section>
          {% endif %}
        {% endwith %}
      </footer>
    {% endif %}
  </article>
{% endblock %}

my_project/templates/post/form.html
{% extends parent_template|default:"post/base.html" %}

{% block title %}
  {{ block.super }} - {% if update %}Update{% else %}Create{% endif %} Blog Post
{% endblock %}

{% block content %}
  <form
      action="."
      method="post"
  >
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">
      {% if update %}Update{% else %}Create{% endif %} Blog Post
    </button>
  </form>
{% endblock %}

my_project/templates/post/list.html
{% extends parent_template|default:"post/base.html" %}

{% block title %}
  {{ block.super }} - Blog
{% endblock %}

{% block content %}
  <p><a href="{% url 'post_create' %}">Write Blog Post</a><p>
  {% for post in post_list %}
    <article>
      <header>
        <h2>
          <a href="{{ post.get_absolute_url }}">
            {{ post.title|title }}</a>
        </h2>
        <p>
          Written on:
          <time datetime="{{ post.pub_date|date:"Y-m-d" }}">
            {{ post.pub_date|date:"l, F j, Y" }}
          </time>
        </p>
      </header>
      <p>{{ post.text|truncatewords:20 }}</p>
      <p>
        <a href="{{ post.get_absolute_url }}">
          Read more…</a>
      </p>
    </article>
  {% empty %}
    <p><em>No Blog Posts Available</em></p>
  {% endfor %}
{% endblock %}

my_project/templates/root.html
{% extends parent_template|default:"base.html" %}

{% block content %}
  <p>
    Welcome to Startup Organizer, the site built during
    <a href="https://andrewsforge.com">Andrew Pinkham's</a>
    <a href=" https://pywebdev.com">Python Web Development</a>
    class. Please use the navigation links above to roam
    the site.
  </p>
{% endblock %}

my_project/templates/startup/base.html
{% extends parent_template|default:"base.html" %}

my_project/templates/startup/confirm_delete.html
{% extends parent_template|default:"startup/base.html" %}

{% block title %}
  {{ startup.name }}: delete?
{% endblock %}

{% block content %}
  <form
      action="."
      method="post"
  >
    {% csrf_token %}
    <p>
      Are you sure you want to delete startup {{ startup.name }}?
    </p>
    <a href="{{ startup.get_absolute_url }}">
      Cancel
    </a>
    <button type="submit">Delete Startup</button>
  </form>
{% endblock %}

my_project/templates/startup/detail.html
{% extends parent_template|default:"startup/base.html" %}

{% block title %}
  {{ startup.name }}
{% endblock %}

{% block content %}
  <h2>{{ startup.name }}</h2>
  <ul>
    <li>
      <a href="{{ startup.get_update_url }}">
        Update
      </a>
    </li>
    <li>
      <a href="{{ startup.get_delete_url }}">
        Delete
      </a>
    </li>
  </ul>
  <dl>
    <dt>Date Founded</dt>
      <dd>{{ startup.founded_date|date:"F jS, Y" }}</dd>
    <dt>Website</dt>
      <dd>{{ startup.website|urlize }}</dd>
    <dt>Contact</dt>
      <dd>{{ startup.contact }}</dd>

    {% with tag_list=startup.tags.all %}
      <dt>Tag{{ tag_list|pluralize }}</dt>
        {% for tag in tag_list %}
          <dd><a href="{{ tag.get_absolute_url }}">
            {{ tag.name|title }}
          </a></dd>
        {% endfor %}
    {% endwith %}
  </dl>
  {{ startup.description|linebreaks }}
  <section>
    <p><a href="{{ startup.get_newslink_create_url }}">
      Add link to article
    </a></p>
    <ul>
      {% for newslink in startup.newslink_set.all %}
        <li>
          <a href="{{ newslink.link }}">
            {{ newslink.title|title }}</a>
          <a href="{{ newslink.get_update_url }}">
            [Modify Link]</a>
          <a href="{{ newslink.get_delete_url }}">
            [Delete Link]</a>
        </li>
      {% endfor %}
    </ul>
  </section>
{% endblock %}

my_project/templates/startup/form.html
{% extends parent_template|default:"startup/base.html" %}

{% block title %}
  {{ block.super }} - {% if update %}Update{% else %}Create{% endif %} Startup
{% endblock %}

{% block content %}
  <form
      action="."
      method="post"
  >
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">
      {% if update %}Update{% else %}Create{% endif %} Startup
    </button>
  </form>
{% endblock %}

my_project/templates/startup/list.html
{% extends parent_template|default:"startup/base.html" %}

{% block title %}
  {{ block.super }} - Startups
{% endblock %}

{% block content %}
  <h2>Startup List</h2>
  <p><a href="{% url 'startup_create' %}">Add Startup</a></p>
  <ul>
    {% for startup in startup_list %}
      <li>
        <a href="{{ startup.get_absolute_url }}">
          {{ startup.name }}</a>
      </li>
    {% empty %}
      <li><em>No Startups Available</em></li>
    {% endfor %}
  </ul>
{% endblock %}

my_project/templates/tag/base.html
{% extends parent_template|default:"base.html" %}

my_project/templates/tag/confirm_delete.html
{% extends parent_template|default:"tag/base.html" %}

{% block title %}
  {{ tag.name }}: delete?
{% endblock %}

{% block content %}
  <form
      action="."
      method="post"
  >
    {% csrf_token %}
    <p>
      Are you sure you want to delete tag {{ tag.name }}?
    </p>
    <a href="{{ tag.get_absolute_url }}">
      Cancel
    </a>
    <button type="submit">Delete Tag</button>
  </form>
{% endblock %}

my_project/templates/tag/detail.html
{% extends parent_template|default:"tag/base.html" %}

{% block title %}
  {{ tag.name|title }}
{% endblock %}

{% block content %}
  <h2>{{ tag.name|title }}</h2>
  <ul>
    <li>
      <a href="{{ tag.get_update_url }}">
        Update
      </a>
    </li>
    <li>
      <a href="{{ tag.get_delete_url }}">
        Delete
      </a>
    </li>
  </ul>
  {% if tag.startup_set.all %}
    <section>
      <h3>Startup{{ tag.startup_set.count|pluralize }}</h3>
      <p>
        Tag is associated with
        {{ tag.startup_set.count }}
        startup{{ tag.startup_set.count|pluralize }}.
      </p>
      <ul>
        {% for startup in tag.startup_set.all %}
          <li><a href="{{ startup.get_absolute_url }}">
            {{ startup.name }}
          </a></li>
        {% endfor %}
      </ul>
    </section>
  {% endif %}
{% endblock %}

my_project/templates/tag/form.html
{% extends parent_template|default:"tag/base.html" %}

{% block title %}
  {{ block.super }} - {% if update %}Update{% else %}Create{% endif %} Tag
{% endblock %}

{% block content %}
  <form
      action="."
      method="post"
  >
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">
      {% if update %}Update{% else %}Create{% endif %} Tag
    </button>
  </form>
{% endblock %}

my_project/templates/tag/list.html
{% extends parent_template|default:"tag/base.html" %}

{% block title %}
  {{ block.super }} - Tag List
{% endblock %}

{% block content %}
  <h2>Tag List</h2>
  <p><a href="{% url 'tag_create' %}">Add New Tag</a><p>
  <ul>
    {% for tag in tag_list %}
      <li>
        <a href="{{ tag.get_absolute_url }}">
          {{ tag.name|title }}</a>
      </li>
    {% empty %}
      <li><em>There are currently no Tags available.</em></li>
    {% endfor %}
  </ul>
{% endblock %}